// Test generated by RoostGPT for test Unit-test using AI Type Open AI and AI Model gpt-4

package com.bootexample4.products.controller;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.when;

import java.util.Optional;

import com.bootexample4.products.model.Product;
import com.bootexample4.products.repository.ProductRepository;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;

public class ProductController_createProduct_36b748883e_Test {

    @InjectMocks
    private ProductController productController;

    @Mock
    private ProductRepository productRepository;

    @BeforeEach
    public void init() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testCreateProduct_success() {
        Product product = new Product();
        product.setId(1L);
        product.setName("Test Product");
        // TODO: Set other product properties

        when(productRepository.save(product)).thenReturn(product);

        Product createdProduct = productController.createProduct(product);
        assertEquals(product, createdProduct);
    }

    @Test
    public void testCreateProduct_failure() {
        Product product = new Product();
        product.setId(1L);
        product.setName("Test Product");
        // TODO: Set other product properties

        when(productRepository.save(product)).thenThrow(new RuntimeException("Product creation failed"));

        try {
            productController.createProduct(product);
        } catch (Exception e) {
            assertEquals("Product creation failed", e.getMessage());
        }
    }
}
