// Test generated by RoostGPT for test roost-test using AI Type Open AI and AI Model gpt-4

package com.bootexample4.products.controller;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.when;

import java.util.Optional;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;

import com.bootexample4.products.model.Product;
import com.bootexample4.products.repository.ProductRepository;

public class ProductController_createProduct_5fee6d5a95_Test {

    @InjectMocks
    private ProductController productController;

    @Mock
    private ProductRepository productRepository;

    @BeforeEach
    void setUp() {
        MockitoAnnotations.openMocks(this);
    }

    @Test
    public void testCreateProduct_Success() {
        Product product = new Product();
        product.setId(1);
        product.setName("TestProduct");
        product.setPrice(200.00);

        when(productRepository.save(product)).thenReturn(product);

        Product createdProduct = productController.createProduct(product);

        assertEquals(product, createdProduct);
    }

    @Test
    public void testCreateProduct_Failure() {
        Product product = new Product();
        product.setId(2);
        product.setName("TestProduct2");
        product.setPrice(300.00);

        when(productRepository.save(product)).thenReturn(null);

        Product createdProduct = productController.createProduct(product);

        assertEquals(null, createdProduct);
    }
}
