// Test generated by RoostGPT for test roost-test using AI Type Open AI and AI Model gpt-4

package com.bootexample4.products.controller;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.http.ResponseEntity;

import java.util.Optional;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.*;

import com.bootexample4.products.model.Product;
import com.bootexample4.products.repository.ProductRepository;

@ExtendWith(MockitoExtension.class)
public class ProductController_deleteProduct_8aa83376b7_Test {

    @InjectMocks
    ProductController productController;

    @Mock
    ProductRepository productRepository;

    @Test
    public void testDeleteProduct_Success() {
        Long id = 1L; // TODO: Change this to the id of the product you want to delete.
        Product product = new Product();
        when(productRepository.findById(id)).thenReturn(Optional.of(product));
        ResponseEntity<Object> response = productController.deleteProduct(id);
        verify(productRepository, times(1)).delete(product);
        assertEquals(200, response.getStatusCodeValue());
    }

    @Test
    public void testDeleteProduct_NotFound() {
        Long id = 1L; // TODO: Change this to the id of the product you want to delete.
        when(productRepository.findById(id)).thenReturn(Optional.empty());
        ResponseEntity<Object> response = productController.deleteProduct(id);
        assertEquals(404, response.getStatusCodeValue());
    }
}
