/*
Test generated by RoostGPT for test newtest using AI Type Azure Open AI and AI Model roost-gpt4-32k

{
  background: 'Given the base URL is "http://localhost:8080"',
  rule: null,
  scenario: 'Delete an existing product\r\n' +
    '    Given there is an existing product with ID 1\r\n' +
    '    When the client sends a DELETE request to "/api/products/1"\r\n' +
    '    Then the response status code should be 200\r\n' +
    '    And the product with ID 1 should no longer exist',
  title: 'Delete an existing product'
}

*/
package com.bootexample4.RoostTest;

import org.junit.Test;
import static io.restassured.RestAssured.given;
import static org.hamcrest.Matchers.*;

public class DeleteAnExistingProductTest {

    /* Test Scenario: Delete an existing product
     * Given there is an existing product with ID 1
     * When the client sends a DELETE request to "/api/products/1"
     * Then the response status code should be 200
     * And the product with ID 1 should no longer exist
     */
    @Test
    public void deleteAnExistingProduct() {
        given().
            baseUri(System.getenv("API_HOST")).
        when().
            delete("/api/products/1").
        then().
            assertThat().
            statusCode(200).
            body("id", not(hasItem("1")));

        // Verify the product with id 1 is no longer exist
        given().
            baseUri(System.getenv("API_HOST")).
        when().
            get("/api/products/1").
        then().
            assertThat().
            statusCode(404);
    }
}
