/*
Test generated by RoostGPT for test newtest using AI Type Azure Open AI and AI Model roost-gpt4-32k

{
  background: 'Given the base URL is "http://localhost:8080"',
  rule: null,
  scenario: 'Get a product by ID\r\n' +
    '    Given there is an existing product with ID 1\r\n' +
    '    When the client sends a GET request "/api/products/1" to get a product by its id\r\n' +
    '    Then the response status code should be 200\r\n' +
    '    And the response should contain the product with ID 1',
  title: 'Get a product by ID'
}

*/
package com.bootexample4.RoostTest;

import io.restassured.RestAssured;
import io.restassured.http.ContentType;
import io.restassured.response.Response;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import static io.restassured.RestAssured.given;

public class getAProductByIdTest {

    @Before
    public void setBaseUri () {
        RestAssured.baseURI = System.getenv("API_HOST");
    }

    @Test
    public void testGetAProductById() {
        // Given there is an existing product with ID 1
        int productId = 1;

        // When the client sends a GET request "/products/1" to get a product by its id
        Response response = 
            given()
                .contentType(ContentType.JSON)
                .accept(ContentType.JSON)
                .pathParam("id", productId)
            .when()
                .get("/api/products/{id}");

        // Then the response status code should be 200
        Assert.assertEquals("Status Check Passed!", 200, response.getStatusCode());

        // And the response should contain the product with ID 1
        int actualProductId = response.jsonPath().getInt("id");
        Assert.assertEquals("Id check passed!", productId, actualProductId);
    }
}
