/*
Test generated by RoostGPT for test newtest using AI Type Azure Open AI and AI Model roost-gpt4-32k

{
  background: 'Given the base URL is "http://localhost:8080"',
  rule: null,
  scenario: 'Get a product by ID\r\n' +
    '    Given there is an existing product with ID 1\r\n' +
    '    When the client sends a GET request "/api/products/1" to get a product by its id\r\n' +
    '    Then the response status code should be 200\r\n' +
    '    And the response should contain the product with ID 1',
  title: 'Get a product by ID'
}

*/
package com.bootexample4.RoostTest;

import io.restassured.http.ContentType;
import org.junit.jupiter.api.Test;
import static io.restassured.RestAssured.*;
import static org.hamcrest.Matchers.*;

class getAProductByIdTest {

    @Test
    public void testGetAProductById() {
        // Scenario: Get a product by ID
        String base_url = System.getenv("API_HOST");

        // Given there is an existing product with ID 1
        int productID = 1;

        // When the client sends a GET request "/api/products/1" to get a product by its id
        given()
            .baseUri(base_url)
            .contentType(ContentType.JSON)
        .when()
            .get("/api/products/" + productID)

        // Then the response status code should be 200
        .then()
            .statusCode(200)

        // And the response should contain the product with ID 1
        .body("id", equalTo(productID));
    }
}
