/*
Test generated by RoostGPT for test newtest using AI Type Azure Open AI and AI Model roost-gpt4-32k

{
  background: 'Given the base URL is "http://localhost:8080"',
  rule: null,
  scenario: 'Get all products\r\n' +
    '    When the client sends a GET request "/api/products" to get the list of all products\r\n' +
    '    Then the list of products returned should be empty',
  title: 'Get all products'
}

*/
package com.bootexample4.RoostTest;

import static io.restassured.RestAssured.given;
import org.testng.annotations.Test;
import org.apache.http.HttpStatus;
import org.json.JSONArray;

public class getAllProductsTest {

    /* This test ensures that calling the getAllProducts API for an empty product list returns an empty list. */
    @Test
    public void testGetAllProductsReturnsEmptyList() {
        String url = System.getenv("API_HOST") + "/api/products";

        JSONArray expectedResponse = new JSONArray();

        given()
            .when()
                .get(url)
            .then()
                .assertThat()
                .statusCode(HttpStatus.SC_OK)
                .body(is(expectedResponse));
    }

    private String is(JSONArray expectedResponse) {
        return expectedResponse.toString();
    }
}
