/*
Test generated by RoostGPT for test Integrationtest using AI Type Open AI and AI Model gpt-4

{
  background: 'Given the base URL is "http://localhost:8080"',
  rule: null,
  scenario: 'Get a product by ID\r\n' +
    '    Given there is an existing product with ID 1\r\n' +
    '    When the client sends a GET request "/api/products/1" to get a product by its id\r\n' +
    '    Then the response status code should be 200\r\n' +
    '    And the response should contain the product with ID 1',
  title: 'Get a product by ID'
}

*/
package com.bootexample4.RoostTest;

import org.junit.jupiter.api.Test;
import static io.restassured.RestAssured.*;
import static org.hamcrest.Matchers.*;

public class GetAProductByIdTest {

    // Scenario: Get a product by ID
    @Test
    public void testGetProductById() {

        // Given there is an existing product with ID 1
        String productId = "1";
        String baseUrl = System.getenv("API_HOST");

        // When the client sends a GET request "/api/products/1" to get a product by its id
        given()
            .baseUri(baseUrl)
            .basePath("/api/products/" + productId)
        .when()
            .get()
        .then()
            // Then the response status code should be 200
            .statusCode(200)
            // And the response should contain the product with ID 1
            .body("id", equalTo(productId));
    }
}
