/*
Test generated by RoostGPT for test Integrationtest using AI Type Open AI and AI Model gpt-4

{
  background: 'Given the base URL is "http://localhost:8080"',
  rule: null,
  scenario: 'Get all products\r\n' +
    '    When the client sends a GET request "/api/products" to get the list of all products\r\n' +
    '    Then the list of products returned should be empty',
  title: 'Get all products'
}

*/
package com.bootexample4.RoostTest;

import io.restassured.RestAssured;
import io.restassured.http.ContentType;
import io.restassured.response.Response;
import org.junit.Assert;
import org.junit.BeforeClass;
import org.junit.Test;

import static io.restassured.RestAssured.given;

public class GetAllProductsTest {

    @BeforeClass
    public static void setup() {
        RestAssured.baseURI = System.getenv("API_HOST");
    }

    @Test
    public void testGetAllProducts() {
        // Given the client sends a GET request "/api/products" to get the list of all products
        Response response = given()
                .when()
                .get("/api/products");

        // Then the list of products returned should be empty
        Assert.assertEquals("Expected status code is 200", 200, response.statusCode());
        Assert.assertEquals("Expected content type is JSON", ContentType.JSON, response.getContentType());
        Assert.assertTrue("Response body should be empty", response.getBody().jsonPath().getList("$").isEmpty());
    }
}
