// Test generated by RoostGPT for test divyesh-31oct using AI Type Open AI and AI Model gpt-4

package com.bootexample4.products.model;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;

public class Product_getPrice_d2cb73a47d_Test {

    @Test
    public void testGetPrice_PositiveScenario() {
        // Arrange
        Product product = Mockito.mock(Product.class);
        Mockito.when(product.getPrice()).thenReturn(100.0);

        // Act
        double result = product.getPrice();

        // Assert
        Assertions.assertEquals(100.0, result, "The price should be 100.0");
    }

    @Test
    public void testGetPrice_ZeroScenario() {
        // Arrange
        Product product = Mockito.mock(Product.class);
        Mockito.when(product.getPrice()).thenReturn(0.0);

        // Act
        double result = product.getPrice();

        // Assert
        Assertions.assertEquals(0.0, result, "The price should be 0.0");
    }
}
