// Test generated by RoostGPT for test roost-test using AI Type Open AI and AI Model gpt-4

package com.bootexample4.products.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class Product_setId_e7f341730a_Test {

    @Mock
    private Product product;

    @BeforeEach
    public void setUp() {
        MockitoAnnotations.openMocks(this);
        product = new Product();
    }

    @Test
    public void testSetIdSuccess() {
        Long expectedId = 123L;
        product.setId(expectedId);
        assertEquals(expectedId, product.getId(), "The set ID does not match the expected ID");
    }

    @Test
    public void testSetIdNull() {
        product.setId(null);
        assertEquals(null, product.getId(), "The set ID should be null");
    }
}
