// Test generated by RoostGPT for test roost-test using AI Type Open AI and AI Model gpt-4

package com.bootexample4.products.model;

import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.mockito.Mockito;

public class Product_setDescription_5d6a2c2267_Test {
    private Product product;

    @Before
    public void setUp() {
        product = new Product();
    }

    @Test
    public void testSetDescription_success() {
        String description = "This is a product description";
        product.setDescription(description);
        Assert.assertEquals("Product description should match", description, product.getDescription());
    }

    @Test
    public void testSetDescription_empty() {
        String description = "";
        product.setDescription(description);
        Assert.assertEquals("Product description should match", description, product.getDescription());
    }

    @Test
    public void testSetDescription_null() {
        product.setDescription(null);
        Assert.assertNull("Product description should be null", product.getDescription());
    }
}
