// Test generated by RoostGPT for test dmunit-2507 using AI Type Open AI and AI Model gpt-4

package com.bootexample4.products.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class Product_setDescription_5d6a2c2267_Test {

    private Product product;

    @BeforeEach
    public void setup() {
        product = new Product();
    }

    @Test
    public void testSetDescription_Success() {
        String expectedDescription = "This is a test product";
        product.setDescription(expectedDescription);
        assertEquals(expectedDescription, product.getDescription());
    }

    @Test
    public void testSetDescription_Null() {
        String expectedDescription = null;
        product.setDescription(expectedDescription);
        assertEquals(expectedDescription, product.getDescription());
    }

}
