// Test generated by RoostGPT for test java-test using AI Type Open AI and AI Model gpt-4

package com.bootexample4.products.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.mock.mockito.MockBean;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.when;

@SpringBootTest
public class Product_getName_8400ac6fb7_Test {

    @MockBean
    private Product product;

    @BeforeEach
    public void setUp() {
        Mockito.reset(product);
    }

    @Test
    public void testGetName_Success() {
        String expectedName = "Product1";
        when(product.getName()).thenReturn(expectedName);
        String actualName = product.getName();
        assertEquals(expectedName, actualName);
    }

    @Test
    public void testGetName_Null() {
        when(product.getName()).thenReturn(null);
        String actualName = product.getName();
        assertEquals(null, actualName);
    }
}
