// Test generated by RoostGPT for test dmtestunit using AI Type Open AI and AI Model gpt-4

package com.bootexample4.products.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class Product_setId_e7f341730a_Test {

    private Product product;

    @BeforeEach
    public void setUp() {
        product = new Product();
    }

    @Test
    public void testSetIdSuccess() {
        Long expectedId = 1L;
        product.setId(expectedId);
        assertEquals(expectedId, product.getId(), "The ID set in the product does not match the expected ID");
    }

    @Test
    public void testSetIdNull() {
        product.setId(null);
        assertEquals(null, product.getId(), "The ID set in the product is not null as expected");
    }
}
