// Test generated by RoostGPT for test roost-test using AI Type Open AI and AI Model gpt-4

package com.bootexample4.products.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class Product_getPrice_d97185b3e6_Test {
    
    private Product product;

    @BeforeEach
    public void setUp() {
        product = new Product();
    }

    @Test
    public void testGetPrice_WhenPriceIsSet() {
        double expectedPrice = 100.0;
        product.setPrice(expectedPrice); // TODO: Change the price value as per your use case
        double actualPrice = product.getPrice();
        assertEquals(expectedPrice, actualPrice, "Price did not match");
    }

    @Test
    public void testGetPrice_WhenPriceIsNotSet() {
        double expectedPrice = 0.0;
        double actualPrice = product.getPrice();
        assertEquals(expectedPrice, actualPrice, "Price did not match");
    }
}
