// Test generated by RoostGPT for test java-test using AI Type Open AI and AI Model gpt-4

package com.bootexample4.products.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;
import static org.assertj.core.api.Assertions.assertThat;

@SpringBootTest
public class Product_getDescription_b1844ea396_Test {

    private Product product;

    @BeforeEach
    public void setup() {
        product = new Product();
    }

    @Test
    public void testGetDescription_whenDescriptionIsSet() {
        String expectedDescription = "This is a product description";
        product.setDescription(expectedDescription);
        String actualDescription = product.getDescription();
        assertThat(actualDescription).isEqualTo(expectedDescription);
    }

    @Test
    public void testGetDescription_whenDescriptionIsNotSet() {
        String actualDescription = product.getDescription();
        assertThat(actualDescription).isNull();
    }
}
