// Test generated by RoostGPT for test dmunit-2507 using AI Type Open AI and AI Model gpt-4

package com.bootexample4.products.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class Product_getDescription_ca387c4bd2_Test {

    private Product product;

    @BeforeEach
    public void setUp() {
        product = Mockito.mock(Product.class);
    }

    @Test
    public void testGetDescription_Success() {
        // TODO: Replace "Test Description" with the actual description you want to test
        String expectedDescription = "Test Description";
        Mockito.when(product.getDescription()).thenReturn(expectedDescription);

        String actualDescription = product.getDescription();

        assertEquals(expectedDescription, actualDescription);
    }

    @Test
    public void testGetDescription_Null() {
        String expectedDescription = null;
        Mockito.when(product.getDescription()).thenReturn(expectedDescription);

        String actualDescription = product.getDescription();

        assertEquals(expectedDescription, actualDescription);
    }
}
