// Test generated by RoostGPT for test java-dm-test using AI Type Azure Open AI and AI Model roost-gpt4-32k

package com.bootexample4.products.model;

import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.junit.MockitoJUnitRunner;

@RunWith(MockitoJUnitRunner.class)
public class Product_setName_5d23a892d9_Test {

    @Test
    public void testSetName() {
        Product product = new Product();
        product.setName("testProduct");
        Assert.assertNotNull(product.getName());
        Assert.assertEquals("testProduct", product.getName());
    }

    @Test
    public void testSetNameNull() {
        Product product = new Product();
        product.setName(null);
        Assert.assertNull(product.getName());
    }
}
