// Test generated by RoostGPT for test dmunit-2507 using AI Type Open AI and AI Model gpt-4

package com.bootexample4.products.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;

import static org.junit.jupiter.api.Assertions.*;

class Product_setId_e7f341730a_Test {

    private Product product;

    @BeforeEach
    void setUp() {
        MockitoAnnotations.openMocks(this);
        product = new Product();
    }

    @Test
    void setId_withValidId() {
        Long expectedId = 1L;
        product.setId(expectedId);
        assertEquals(expectedId, product.getId(), "The expected id does not match the actual id");
    }

    @Test
    void setId_withNullId() {
        product.setId(null);
        assertNull(product.getId(), "The id is not null");
    }
}
