// Test generated by RoostGPT for test roost-test using AI Type Open AI and AI Model gpt-4

package com.bootexample4.products.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.MockitoAnnotations;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;

public class Product_getId_eb19b6a6d6_Test {

    @InjectMocks
    private Product product;

    @BeforeEach
    public void init() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testGetIdSuccess() {
        Long expectedId = 100L;
        product.setId(expectedId);
        Long actualId = product.getId();
        assertNotNull(actualId);
        assertEquals(expectedId, actualId);
    }

    @Test
    public void testGetIdFailure() {
        Long actualId = product.getId();
        assertEquals(null, actualId);
    }
}
