// Test generated by RoostGPT for test java-dm-test using AI Type Azure Open AI and AI Model roost-gpt4-32k

package com.bootexample4.products.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class Product_getDescription_b1844ea396_Test {

    private Product product;

    @BeforeEach
    public void setUp() {
        product = new Product();
    }

    @Test
    public void testGetDescription_Success() {
        String testDescription = "Test Product Description";
        product.setDescription(testDescription);
        String description = product.getDescription();

        assertEquals(testDescription, description, "The description returned was not as expected");
    }

    @Test
    public void testGetDescription_NullDescription() {
        String description = product.getDescription();

        assertEquals(null, description, "The description returned was not null as expected when description is not set");
    }
}
