// Test generated by RoostGPT for test roost-test using AI Type Open AI and AI Model gpt-4

package com.bootexample4.products.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

public class Product_setPrice_fa182f5c65_Test {

    private Product product;

    @BeforeEach
    public void setup() {
        product = new Product();
    }

    @Test
    public void testSetPricePositive() {
        double price = 100.0;
        product.setPrice(price);
        assertEquals(price, product.getPrice(), "The price should match the set value");
    }

    @Test
    public void testSetPriceZero() {
        double price = 0.0;
        product.setPrice(price);
        assertEquals(price, product.getPrice(), "The price should match the set value");
    }

    @Test
    public void testSetPriceNegative() {
        double price = -100.0;
        try {
            product.setPrice(price);
            fail("Expected an IllegalArgumentException to be thrown");
        } catch (IllegalArgumentException e) {
            assertEquals("Price cannot be negative", e.getMessage());
        }
    }
}
