// Test generated by RoostGPT for test dmunit-2507 using AI Type Open AI and AI Model gpt-4

package com.bootexample4.products.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class Product_setPrice_fa182f5c65_Test {

    private Product product;

    @BeforeEach
    public void setUp() {
        product = new Product();
    }

    @Test
    public void testSetPrice_PositivePrice() {
        double price = 100.0;
        product.setPrice(price);
        assertEquals(price, product.getPrice(), "The price should be set correctly");
    }

    @Test
    public void testSetPrice_ZeroPrice() {
        double price = 0.0;
        product.setPrice(price);
        assertEquals(price, product.getPrice(), "The price should be set correctly even if it is zero");
    }

    @Test
    public void testSetPrice_NegativePrice() {
        double price = -100.0;
        product.setPrice(price);
        assertEquals(price, product.getPrice(), "The price should be set correctly even if it is negative");
    }
}
