// Test generated by RoostGPT for test java-test using AI Type Open AI and AI Model gpt-4

package com.bootexample4.products.model;

import org.junit.Before;
import org.junit.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import static org.junit.Assert.assertEquals;

public class Product_setId_04a8e16b7c_Test {

    @Mock
    private Product product;

    @Before
    public void setup() {
        MockitoAnnotations.initMocks(this);
        product = new Product();
    }

    @Test
    public void testSetId_ValidId() {
        Long expectedId = 1L;
        product.setId(expectedId);
        assertEquals(expectedId, product.getId());
    }

    @Test
    public void testSetId_NullId() {
        product.setId(null);
        assertEquals(null, product.getId());
    }
}
