// Test generated by RoostGPT for test dmunit-2507 using AI Type Open AI and AI Model gpt-4

package com.bootexample4.products.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class Product_getPrice_d97185b3e6_Test {

    private Product product;

    @BeforeEach
    public void setUp() {
        product = new Product();
    }

    @Test
    public void testGetPrice_whenPriceIsSet() {
        double expectedPrice = 100.0;
        product.setPrice(expectedPrice);  // TODO: Change the price value as per your requirement

        double actualPrice = product.getPrice();

        assertEquals(expectedPrice, actualPrice, "The expected price did not match the actual price");
    }

    @Test
    public void testGetPrice_whenPriceIsNotSet() {
        double defaultPrice = 0.0;

        double actualPrice = product.getPrice();

        assertEquals(defaultPrice, actualPrice, "The expected default price did not match the actual price");
    }
}
