// Test generated by RoostGPT for test roost-test using AI Type Open AI and AI Model gpt-4

package com.bootexample4.products.model;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.MockitoAnnotations;

public class Product_getName_4ad76af4d7_Test {

    @InjectMocks
    private Product product;

    @BeforeEach
    public void setup() {
        MockitoAnnotations.openMocks(this);
    }

    @Test
    public void testNameGetterWhenNameIsSet() {
        String expectedName = "Test Product";
        product.setName(expectedName);
        String actualName = product.getName();
        Assertions.assertEquals(expectedName, actualName, "Product name does not match");
    }

    @Test
    public void testNameGetterWhenNameIsNotSet() {
        String actualName = product.getName();
        Assertions.assertNull(actualName, "Product name should be null");
    }
}
