// Test generated by RoostGPT for test roost-test using AI Type Open AI and AI Model gpt-4

package com.bootexample4.products.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.when;

public class Product_getDescription_ca387c4bd2_Test {

    @Mock
    private Product product;

    @BeforeEach
    public void setup() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testGetDescription_Success() {
        String expectedDescription = "This is a test product";
        when(product.getDescription()).thenReturn(expectedDescription);

        String actualDescription = product.getDescription();

        assertEquals(expectedDescription, actualDescription);
    }

    @Test
    public void testGetDescription_Null() {
        String expectedDescription = null;
        when(product.getDescription()).thenReturn(expectedDescription);

        String actualDescription = product.getDescription();

        assertEquals(expectedDescription, actualDescription);
    }
}
