// Test generated by RoostGPT for test java-test using AI Type Open AI and AI Model gpt-4

package com.bootexample4.products.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;

import static org.assertj.core.api.Assertions.assertThat;

public class Product_setDescription_b4ccff923c_Test {

    private Product product;

    @BeforeEach
    void setUp() {
        product = new Product();
    }

    @Test
    public void testSetDescription_validDescription() {
        String description = "This is a valid description";
        product.setDescription(description);
        assertThat(product.getDescription()).isEqualTo(description);
    }

    @Test
    public void testSetDescription_nullDescription() {
        String description = null;
        product.setDescription(description);
        assertThat(product.getDescription()).isNull();
    }

    @Test
    public void testSetDescription_emptyDescription() {
        String description = "";
        product.setDescription(description);
        assertThat(product.getDescription()).isEmpty();
    }

}
